// Generated by reader_util_test.go.
// Only edit to bootstrap new entries or change existing entries.

package fit_test

var decodeTestFiles = [...]struct {
	folder      string
	name        string
	wantErr     bool
	fingerprint uint64
	compress    bool
	dopts       testingDecodeOpts
	skipEncode  bool
}{
	{
		"me",
		"activity-small-fenix2-run.fit",
		false,
		13903750506084204989,
		true,
		tdoAllWithDiscardLogger,
		true, // Decode mismatch due to unknown fields
	},
	{
		"fitsdk",
		"Activity.fit",
		false,
		9672300596765488860,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"MonitoringFile.fit",
		false,
		10897216740120494744,
		true,
		tdoNone,
		true, // Fails because first message has different valid fields (#36)
	},
	{
		"fitsdk",
		"Settings.fit",
		false,
		3764513367232478449,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WeightScaleMultiUser.fit",
		false,
		14269684491750057975,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WorkoutCustomTargetValues.fit",
		false,
		4975066257479915757,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WorkoutIndividualSteps.fit",
		false,
		17191203419508130426,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WorkoutRepeatGreaterThanStep.fit",
		false,
		15582330408656848122,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WorkoutRepeatSteps.fit",
		false,
		1094841760112654858,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WeightScaleSingleUser.fit",
		false,
		15243831000130341762,
		true,
		tdoNone,
		false,
	},
	{
		"python-fitparse",
		"garmin-edge-500-activitiy.fit",
		false,
		15676477887963147959,
		true,
		tdoNone,
		false,
	},
	{
		"python-fitparse",
		"sample-activity-indoor-trainer.fit",
		false,
		10459467613954119461,
		true,
		tdoNone,
		true, // Fails because first message has different valid fields (#36)
	},
	{
		"python-fitparse",
		"compressed-speed-distance.fit",
		false,
		0,
		false,
		tdoNone,
		false,
	},
	{
		"python-fitparse",
		"antfs-dump.63.fit",
		false,
		6818279110294360324,
		true,
		tdoNone,
		true, // Fails because first message has different valid fields (#36)
	},
	{
		"sram",
		"Settings.fit",
		false,
		5227529081664738551,
		true,
		tdoNone,
		true, // Fails due to encoder using profile length for arrays (#37)
	},
	{
		"sram",
		"Settings2.fit",
		false,
		4224699768017778451,
		true,
		tdoNone,
		true, // Fails due to encoder using profile length for arrays (#37)
	},
	{
		"dcrainmaker",
		"Edge810-Vector-2013-08-16-15-35-10.fit",
		false,
		15598302189118229567,
		true,
		tdoNone,
		true, // Fails because first message has different valid fields (#36)
	},
	{
		"misc",
		"2013-02-06-12-11-14.fit",
		false,
		6089168419395578599,
		true,
		tdoNone,
		false,
	},
	{
		"misc",
		"2015-10-13-08-43-15.fit",
		false,
		13511729247596750013,
		true,
		tdoNone,
		false,
	},
	{
		"corrupt",
		"activity-filecrc.fit",
		true,
		11399758616898785635,
		true,
		tdoNone,
		false,
	},
	{
		"corrupt",
		"activity-unexpected-eof.fit",
		true,
		5759083369172998667,
		true,
		tdoNone,
		false,
	},
}
